name: WordPress.org readme/assets update

on:
  push:
    branches:
      - main
    paths:
      - readme.txt
      - .wordpress-org/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    name: Sync readme/assets to wp.org
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: WordPress.org plugin readme/assets update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: dont-mess-up-prod
          ASSETS_DIR: .wordpress-org
          IGNORE_OTHER_FILES: true
